function VUP = calc_viaduto_VUP(coeficientes_VUP, viaduto)

pf_target = coeficientes_VUP.probabilidade_de_falha;
n = coeficientes_VUP.numero_de_analises; % Numeros de avaliações da simulação
%% Dados do problema


kce = coeficientes_VUP.kce;
cv_fc = coeficientes_VUP.cv_fc;
cv_c = coeficientes_VUP.cv_c;
CO2m = coeficientes_VUP.CO2m;
cv_CO2 = coeficientes_VUP.cv_CO2;
URm = coeficientes_VUP.URm;
cv_UR = coeficientes_VUP.cv_UR;

%% Avalia VUP
%VUP = calc_VUP(coeficientes_VUP.dados_cimento, tipo_cimento, fcm, cv_fc, cm, cv_c, CO2m, cv_CO2, URm, cv_UR, ad, kce, pf_target, n);

% Fundação
    VUP.fundacao = calc_VUP(coeficientes_VUP.dados_cimento,...
viaduto.fundacao.tipo_cimento,...
viaduto.fundacao.fck/1E6, cv_fc,...
viaduto.fundacao.c*1000, cv_c, CO2m, cv_CO2, URm, cv_UR, custo_interpolado(...
viaduto.fundacao.fck/1E6, [transpose([coeficientes_VUP.ad_concreto(:).fck]),transpose([coeficientes_VUP.ad_concreto(:).ad])]), kce, pf_target, n);
% Pilares
    VUP.pilares = calc_VUP(coeficientes_VUP.dados_cimento,...
viaduto.pilares.tipo_cimento,...
viaduto.pilares.fck/1E6, cv_fc,...
viaduto.pilares.c*1000, cv_c, CO2m, cv_CO2, URm, cv_UR, custo_interpolado(...
viaduto.pilares.fck/1E6, [transpose([coeficientes_VUP.ad_concreto(:).fck]),transpose([coeficientes_VUP.ad_concreto(:).ad])]), kce, pf_target, n);
% Travessas
    VUP.travessas = calc_VUP(coeficientes_VUP.dados_cimento,...
viaduto.travessas.tipo_cimento,...
viaduto.travessas.fck/1E6, cv_fc,...
viaduto.travessas.c*1000, cv_c, CO2m, cv_CO2, URm, cv_UR, custo_interpolado(...
viaduto.travessas.fck/1E6, [transpose([coeficientes_VUP.ad_concreto(:).fck]),transpose([coeficientes_VUP.ad_concreto(:).ad])]), kce, pf_target, n);
% Longarinas
    VUP.longarinas = calc_VUP(coeficientes_VUP.dados_cimento,...
viaduto.longarinas.tipo_cimento,...
viaduto.longarinas.fck/1E6, cv_fc,...
viaduto.longarinas.c*1000, cv_c, CO2m, cv_CO2, URm, cv_UR, custo_interpolado(...
viaduto.longarinas.fck/1E6, [transpose([coeficientes_VUP.ad_concreto(:).fck]),transpose([coeficientes_VUP.ad_concreto(:).ad])]), kce, pf_target, n);
% Lajes
    VUP.lajes = calc_VUP(coeficientes_VUP.dados_cimento,...
viaduto.lajes.tipo_cimento,...
viaduto.lajes.fck/1E6, cv_fc,...
viaduto.lajes.c*1000, cv_c, CO2m, cv_CO2, URm, cv_UR, custo_interpolado(...
viaduto.lajes.fck/1E6, [transpose([coeficientes_VUP.ad_concreto(:).fck]),transpose([coeficientes_VUP.ad_concreto(:).ad])]), kce, pf_target, n);

% Calcula o mínimo
z = struct2cell(VUP(:)); 
VUP.min = min(reshape([z{:}],size(z)));
end


